name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Update version in manifest.json
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          sed -i "s/\"version\": \".*\"/\"version\": \"$VERSION\"/" manifest.json
      
      - name: Create ZIP file
        run: zip -r coretax-bulk-download.zip . -x "*.git*" ".github/*"
      
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: coretax-bulk-download.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}